### ISSUE TITLE
Getting IllegalArgumentException error while compiling

### ISSUE THREAD

**Issue by mitulbhalia** [jasonkneen/TiExpansionFiles#4]
I am getting below error while compiling the code with the module.
I need to use older sdks like 4.x.x or 5.x.x

[ERROR] :  TiApplication: (main) [179,1388] Sending event: exception on thread: main msg:java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.licensing.ILicensingService }; Titanium 3.5.1,2015/03/05 10:08,96875c9
[ERROR] :  TiApplication: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.licensing.ILicensingService }

**Comment by jasonkneen** [comment]
Minimum SDK is 6.0.0.

**Comment by mitulbhalia** [comment]
But i am using 1.0 and this supports older sdks....
