### ISSUE TITLE
Cannot access video files directly

### ISSUE THREAD

**Issue by eggin** [jasonkneen/TiExpansionFiles#5]
Because the Ti.Media.VideoPlayer cannot use a blob for content in Android, video files have to be extracted from the expansion file before they can be played – which takes up additional space on the device and requires an additional layer of code to check whether the files have been extracted or not.

It would appear from the Google ExpansionFile documentation that implementing a concrete instance of the APEZProvider class (and adding the appropriate authority to the manifest) would allow direct access to (uncompressed) video files inside the ExansionFile obb, without having to extract them.

It would be exceptionally useful to be able to access the files directly.

Two examples are here:
http://www.bowsoftware.co.uk/blog/2013/september/18/how-to-stream-video-from-a-zipped-apk-resource-into-videoview/
http://stackoverflow.com/questions/9623350/where-is-the-samplezipfileprovider-class

**Comment by AppWerft** [comment]
I have same issue.
