### ISSUE TITLE
Problems with licencing

### ISSUE THREAD

**Issue by AppWerft** [jasonkneen/TiExpansionFiles#6]
Hi Jason,
my appid is de.appwerft.lumidium the expansionfile is named 'main.4.de.appwerft.lumidium.obb' and is a zip file. File is in store uploaded.

On start window open I coded:
require('ti.expansionfiles').downloadXAPKs({
		mainFile : {
			version : 3,
			size : 26154938
		}
	});
Size is this one from filesystem, I installed all extras in android sdk ;-)

Here my log:
~~~
-- Start application log -----------------------------------------------------
[INFO] :   TiApplication: (main) [50,114] Titanium Javascript runtime: v8
[DEBUG] :  TiexpansionfilesModule: (main) [47,161] inside onAppCreate
[DEBUG] :  Module: Loading module: expansionfiles -> Resources/expansionfiles.js
[DEBUG] :  Atlas: Validating map...
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [480,480] [ti.expansionfiles.TiexpansionfilesModule$XAPKFile@15f5eaaf]
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [0,480] initialize. RootActivity: de.appwerft.lumidium.LumidiumActivity
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [3,483] expansionFilesDelivered? checking files:
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [0,483] 	file: main.3.de.appwerft.lumidium.obb
[DEBUG] :  LVLDL: Service Bound
[DEBUG] :  TiexpansionfilesModule: (main) [107,590] onServiceConnected
[DEBUG] :  TiexpansionfilesModule: (main) [0,590] onServiceConnected
[DEBUG] :  D/com.android.vending.expansion.downloader.R: static initializer
[INFO] :   downloaderServiceConnected
[INFO] :   downloaderServiceConnected
[DEBUG] :  DownloaderService: salt: [170,218,244,241,16,93,95,38,195,124,122,151,45,178,176,189,104,103,50,103]
[DEBUG] :  DownloaderService: public key: MIIBIjANBgkqhkiG9******Sn8F44e7RcWzzNuV6XMWMN32pjslIkY/wPoRDe6lYm2ZmyAnhrer5UKbbTEdTD1HXc8ROUlRob40caHCq9O2NkZLJK2HZ+HPLs6PUa63hoKGE9iqVPes3iok0y9J1SI6k1fM/VcZDSy8IWmAyh/i4L/Agwu6uTepAb8lSSGGrPnDMA1gVwIDAQAB
[INFO] :   LicenseChecker: Binding to licensing service.
[DEBUG] :  AndroidRuntime: Shutting down VM
[INFO] :   Process: Sending signal. PID: 7023 SIG: 9
~~~

Any ideas?

**Comment by omorandi** [comment]
@AppWerft, I guess that your request in downloadXAPKs() should be for version 4 of the file, not 3.
Also, for a complete crash log you might check out the logcat from DDMS, which will also contain the offending exception

**Comment by AppWerft** [comment]
Thanks @omorandi . Currently all versions are '4', (appVersion,oob-version) Perhaps I have to wait for deploying by google ..

Here my ddms log:
01-18 13:31:59.141: W/AppSecurityPermissions(29511): Couldn't retrieve permissions for package:de.appwerft.lumidium
01-18 13:32:02.462: I/ActivityManager(742): START u0 {act=android.intent.action.UNINSTALL_PACKAGE dat=package:de.appwerft.lumidium cmp=com.android.packageinstaller/.UninstallerActivity (has extras)} from uid 1000 on display 0
01-18 13:32:03.879: I/ActivityManager(742): Force stopping de.appwerft.lumidium appid=10140 user=-1: uninstall pkg
01-18 13:32:04.004: W/ActivityManager(742): Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:de.appwerft.lumidium flg=0x4000010 (has extras) }: user 10 is stopped
01-18 13:32:04.005: W/ActivityManager(742): Skipping broadcast of Intent { act=android.intent.action.PACKAGE_FULLY_REMOVED dat=package:de.appwerft.lumidium flg=0x4000010 (has extras) }: user 10 is stopped
01-18 13:32:04.191: E/InstalledAppDetails(29511): Exception when retrieving package:de.appwerft.lumidium
01-18 13:32:04.191: E/InstalledAppDetails(29511): android.content.pm.PackageManager$NameNotFoundException: de.appwerft.lumidium
01-18 13:32:04.196: W/AppSecurityPermissions(29511): Couldn't retrieve permissions for package:de.appwerft.lumidium
01-18 13:32:04.220: W/PackageManager(742): Package named 'de.appwerft.lumidium' doesn't exist.
01-18 13:32:04.284: W/PackageManager(742): Package named 'de.appwerft.lumidium' doesn't exist.
01-18 13:32:18.165: D/Finsky(19570): [1] WorkerTask.onPreExecute: Verification Requested for id = 122, data=file:///data/local/tmp/Lumidium.apk flags=114 fromVerificationActivity=false
01-18 13:32:19.724: D/DefContainer(28217): Copying /data/local/tmp/Lumidium.apk to base.apk
01-18 13:32:20.906: D/PackageManager(742): Renaming /data/app/vmdl652243773.tmp to /data/app/de.appwerft.lumidium-1
01-18 13:32:21.045: I/art(742): DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@app@de.appwerft.lumidium-1@base.apk@classes.dex' for file location '/data/app/de.appwerft.lumidium-1/base.apk': Failed to open oat filename for reading: No such file or directory
01-18 13:32:21.045: I/art(742): DexFile_isDexOptNeeded failed to open oat file '/data/app/de.appwerft.lumidium-1/arm/base.odex' for file location '/data/app/de.appwerft.lumidium-1/base.apk': Failed to open oat filename for reading: No such file or directory
01-18 13:32:21.045: I/PackageManager(742): Running dexopt on: /data/app/de.appwerft.lumidium-1/base.apk pkg=de.appwerft.lumidium isa=arm vmSafeMode=false
01-18 13:32:21.079: I/dex2oat(30014): /system/bin/dex2oat --zip-fd=6 --zip-location=/data/app/de.appwerft.lumidium-1/base.apk --oat-fd=7 --oat-location=/data/dalvik-cache/arm/data@app@de.appwerft.lumidium-1@base.apk@classes.dex --instruction-set=arm --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m
01-18 13:32:24.789: W/ActivityManager(742): Skipping broadcast of Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.appwerft.lumidium flg=0x4000010 (has extras) }: user 10 is stopped
01-18 13:32:24.907: D/BackupManagerService(742): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.appwerft.lumidium flg=0x4000010 (has extras) }
01-18 13:32:24.908: W/BackupManagerService(742): Removing schedule queue dupe of de.appwerft.lumidium
01-18 13:32:25.000: I/ConfigFetchService(32351): PackageReceiver: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.appwerft.lumidium flg=0x4000010 cmp=com.google.android.gms/.config.ConfigFetchService$PackageReceiver (has extras) }
01-18 13:32:25.010: I/ConfigFetchService(32351): onStartCommand Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.appwerft.lumidium cmp=com.google.android.gms/.config.ConfigFetchService (has extras) }
01-18 13:32:25.054: D/PackageBroadcastService(32351): Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=de.appwerft.lumidium
01-18 13:32:25.120: I/UpdateIcingCorporaServi(1420): Updating corpora: APPS=de.appwerft.lumidium, CONTACTS=MAYBE
01-18 13:32:25.480: I/ActivityManager(742): START u0 {flg=0x10000000 cmp=de.appwerft.lumidium/.LumidiumActivity} from uid 2000 on display 0
01-18 13:32:25.504: I/ActivityManager(742): Start proc de.appwerft.lumidium for activity de.appwerft.lumidium/.LumidiumActivity: pid=30162 uid=10142 gids={50142, 9997, 3003, 1028, 1015} abi=armeabi-v7a
01-18 13:32:25.646: W/BroadcastQueue(742): Unable to launch app de.appwerft.l2g/10132 for broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:de.appwerft.lumidium flg=0x4000010 (has extras) }: process is bad
01-18 13:32:26.245: I/TiRootActivity(30162): (main) [0,0] checkpoint, on root activity resume. activity = de.appwerft.lumidium.LumidiumActivity@24102ec4
01-18 13:32:26.269: I/ActivityManager(742): START u0 {cmp=de.appwerft.lumidium/org.appcelerator.titanium.TiActivity (has extras)} from uid 10142 on display 0
01-18 13:32:26.777: D/TiexpansionfilesModule(30162): (KrollRuntimeThread) [0,532] initialize. RootActivity: de.appwerft.lumidium.LumidiumActivity
01-18 13:32:26.786: D/TiexpansionfilesModule(30162): (KrollRuntimeThread) [0,541] 	file: main.4.de.appwerft.lumidium.obb
01-18 13:32:26.924: I/ActivityManager(742): Displayed de.appwerft.lumidium/org.appcelerator.titanium.TiActivity: +585ms (total +1s438ms)
01-18 13:32:27.061: E/AndroidRuntime(30162): Process: de.appwerft.lumidium, PID: 30162
01-18 13:32:27.062: W/ActivityManager(742):   Force finishing activity de.appwerft.lumidium/org.appcelerator.titanium.TiActivity
01-18 13:32:27.064: W/ActivityManager(742):   Force finishing activity de.appwerft.lumidium/.LumidiumActivity
01-18 13:32:27.564: W/ActivityManager(742): Activity pause timeout for ActivityRecord{377b2a9e u0 de.appwerft.lumidium/org.appcelerator.titanium.TiActivity t624 f}
