### ISSUE TITLE
Validation not starting after checking expansionFilesDelivered.

### ISSUE THREAD

**Issue by oshevans** [jasonkneen/TiExpansionFiles#8]
I'm not sure if this is related to the downloadXAPKs issue, but what would cause the module not to start validation on a previously downloaded file?

If previously downloaded, the sample zip goes through the validation process after the expansionFilesDelivered check... but when using our own zip file it doesn't.

SAMPLE ZIP - 12001918
```javascrip
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [0,1828] [ti.expansionfiles.TiexpansionfilesModule$XAPKFile@421be388]
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [1,1829] initialize. RootActivity: {app.id}.Activity
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [2,1831] expansionFilesDelivered? checking files:
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [1,1832] 	file: main.34.{app.id}.obb
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [1,1833] validateAPKStarted
```
OUR ZIP - 55355787
```javascrip
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [1,1354] [ti.expansionfiles.TiexpansionfilesModule$XAPKFile@4201ac30]
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [1,1355] initialize. RootActivity: {app.id}.Activity
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [3,1358] expansionFilesDelivered? checking files:
[DEBUG] :  TiexpansionfilesModule: (KrollRuntimeThread) [1,1359] 	file: main.35.{app.id}.obb
```
When using our package, it never goes to 'validateAPKStarted', and we don't hear from the module again.

**Comment by pumapaul** [comment]
I have exactly the same problem (And also the downloadXAPKs issue).

Example expansion file:
After catching the downloadXAPKs error and just calling downloadXAPKs() again in the catch block and waiting for the validation to complete I can access the files inside the expansion file.

With our expansion file:
I try to access it, get the downloadXAPKs error. When I try the workaround that works with the example it never starts validating the already downloaded file.


@oshevans : did you find a workaround or a fix or something?

**Comment by oshevans** [comment]
To be honest... I can't remember how we resolved either of these issues, but we did resolve it and published the app.

By coincidence, we are currently working on an update for the app, so will be looking at the expansion files again over the next couple of days before re-publishing... I'll keep you posted here on how we get on... maybe it will all come back to me (note to self... must rely on Google search less and document more).

**Comment by pumapaul** [comment]
I solved it myself.
The version number I initiated the download with was different from the version number of the expansion file. So while it did download the file, the module couldn't find the file and therefore never validate / use it. Kind of a dumb mistake.

Thanks anyway!
